// <auto-generated />
namespace prsnet.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addedvendorandutilityfieldstouser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedvendorandutilityfieldstouser));
        
        string IMigrationMetadata.Id
        {
            get { return "201810311055575_added vendor and utility fields to user"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
